version: 2
jobs:
  dockerbuild:
    machine: 
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: "Log in to AWS ECR"
          command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 032233938113.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: Build and push Docker image
          command: |
            sha=$CIRCLE_SHA1
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo:$sha .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo:$sha
  deployecs:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run:
          name: install aws & ecs-deploy
          command: |
            sudo wget "https://raw.githubusercontent.com/silinternational/ecs-deploy/develop/ecs-deploy" -O /usr/local/bin/ecs-deploy
            sudo chmod +x /usr/local/bin/ecs-deploy
      - run:
          name: deploying to ECS
          command: |
            sha=$CIRCLE_SHA1
            echo "ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo-demo:$sha --timeout 1800"
            ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo-demo:$sha --timeout 1800
workflows:
  version: 2
  buil&push:
    jobs:
      - dockerbuild:
          filters:
            branches:
              only: main
      - deployecs:
          requires:
            - dockerbuild
          filters:
            branches:
              only: main