version: 2
jobs:
  dockerbuild:
    machine: 
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: install aws
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get update -y
            sudo apt-get install python3.6 -y
            sudo apt-get install python3-setuptools -y
            sudo  easy_install3 pip
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --region $REGION --no-include-email)
      - run:
          name: Build and push Docker image
          command: |
            sha=$CIRCLE_SHA1
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo:$sha .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo:$sha
  deployecs:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run:
          name: install aws & ecs-deploy
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            sudo wget "https://raw.githubusercontent.com/silinternational/ecs-deploy/develop/ecs-deploy" -O /usr/local/bin/ecs-deploy
            sudo chmod +x /usr/local/bin/ecs-deploy
      - run:
          name: deploying to ECS
          command: |
            sha=$CIRCLE_SHA1
            echo "ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo-demo:$sha --timeout 1800"
            ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dockrepo-demo:$sha --timeout 1800
workflows:
  version: 2
  buil&push:
    jobs:
      - dockerbuild:
          filters:
            branches:
              only: main
      - deployecs:
          requires:
            - dockerbuild
          filters:
            branches:
              only: main